### ISSUE TITLE
Safari and iOS  - cordova/phonegap support

### ISSUE THREAD

**Issue by 45kb** [alexgibson/shake.js#20]
Hello, sorry for this issue but I tried to find if there was already something open about this and it seems not.

I just wanted to ask if shake.js works on Safari and iOS using it along with cordova / PhoneGap, as on Android 4.1 works perfectly but on ios simulator does not seem to work, so i am just wondering if Safari and iOS in general are both fully supported by shake.js and if is there any tip to make it work on them in case is not supporting them.

Thank you!

**Comment by dandv** [comment]
This plugin won't work in Cordova.

The plugin uses the [devicemotion](https://developer.mozilla.org/en-US/docs/Web/Events/devicemotion) [API](http://w3c.github.io/deviceorientation/spec-source-orientation.html), while Cordova exposes a [`navigator.accelerometer`](http://docs.phonegap.com/en/edge/cordova_accelerometer_accelerometer.md.html) API through a plugin that is (misleadingly?) called [apache.cordova.device-motion](http://plugins.cordova.io/#/package/org.apache.cordova.device-motion)
