### ISSUE TITLE
Put new tag

### ISSUE THREAD

**Issue by sugarshin** [alexgibson/shake.js#24]
In order to utilize the module loader, please have put new tag for bower.

**Comment by tehsis** [comment]
While not ideal, you can just point to the specific commit for that change
until the tag gets created:

bower install shake.js#a9f746db3ce83152ca42799d704bed463a8a19b6 --save

Pablo E. Terradillos

**Comment by alexgibson** [comment]
I will try and get this done soon, sorry for the delay

**Comment by sugarshin** [comment]
@tehsis @alexgibson Thank you!

**Comment by alexgibson** [comment]
https://github.com/alexgibson/shake.js/releases/tag/v1.2.0
