### ISSUE TITLE
passing custom data/parameter to shake event

### ISSUE THREAD

**Issue by sharp-c** [alexgibson/shake.js#30]
sometimes, we need feedback after a shake event, for example, if I can pass shake "strength" to the event, I can do lots of things according to the "strength".

I know we can pass a object named "detail" when create new CustomEvent
```javascript
this.event = new CustomEvent('shake', {
                bubbles: true,
                cancelable: true,
                "detail":{"strength":0}
            });
```
but when we use ` document.createEvent`:
```javascript
this.event = document.createEvent('Event');
            this.event.initEvent('shake', true, true); 
```
I found that it works on my iphone (IOS7.1) and android(V4.4) by adding this line:
```javascript
 this.event.detail={};
```
But it seems this is  ***not documented***  in any official specifications.
So, my question:  is there a good solution to pass custom parameters for `document.createEvent`, thank you.

**Comment by alexgibson** [comment]
We could certainly pass data for browsers that can use `CustomEvent` like you say (pull requests are welcome). 

When it comes to `createEvent` things are a little murky. We could potentially use `initCustomEvent` here instead of `initEvent`, but I believe that method has been deprecated. I'm hesitant to rely on & use undocumented properties generally, as tempting as it may seem.

**Comment by sharp-c** [comment]
Hi Alex, I'd like to send a pull request, but I haven't find any good solution to `createEvent` scenario.
As you said, `initCustomEvent` was deprecated, according to my test, iPhone IOS7.1 and IOS8.0, Android V4.4 and V4.2.1 already don't support initCustomEvent, but CustomEvent works.

**Comment by alexgibson** [comment]
Yeah, id on' think there's a way to do this using `initEvent` but I'd be happy to add it to `CustomEvent`. We'd just need to make sure we add a note to the docs as to this exception.

**Comment by smade77** [comment]
I have a question - what is the strength is undefined? - what would cancel it out or not make it work? I am having an issue with it not working (its attached to button function and google maps api) ... 
Its not working when i shake it yet - when i click the button it works. strange ... am i missing something?

var myShakeEvent = new Shake({
    threshold: 15, // optional shake strength threshold
    timeout: 1000 // optional, determines the frequency of event generation
});
myShakeEvent.start();

var button = document.querySelector('#shakeButton');

window.addEventListener('shake', shakeEventDidOccur, false);
button.addEventListener('click', shakeEventDidOccur);

//function to call when shake occurs
function shakeEventDidOccur (e) {

```
//put your own code here etc.
```

   console.log('Shake, the strength: ' + (e).detail.strength);
}
 This is what i have. - 
![image](https://cloud.githubusercontent.com/assets/12807938/11415258/98911f8a-9465-11e5-86da-f4865fb17c7b.png)

**Comment by alexgibson** [comment]
You need to actually pass the event data. This is not a feature that's yet in the master branch.

**Comment by smade77** [comment]
Hi Alex - how do i do that - pretty new to all this js coding...

**Comment by alexgibson** [comment]
Sorry, I but I don't have time to hand-hold people through adding new features. Look at the initial comment in this issue for a pointer.

**Comment by alexgibson** [comment]
Closing this issue as it's not actually a feature in the current version of the plugin. Pull requests to add said feature as welcome :smile:
