### ISSUE TITLE
One Time Shake event

### ISSUE THREAD

**Issue by usama831** [alexgibson/shake.js#35]
Hi,
I am using this Library & found it very helpful for me,

Now my scenario is:
When One time shake occurs I want to show the images, I found there is no such function
in the Library to do this.
How can I do this via using this library

**Comment by alexgibson** [comment]
I don't quite understand your issue? When a shake occurs, show your images. If you only want the event to happen one time, remove the listener and destroy the plugin instance afterward.

**Comment by usama831** [comment]
I can't understand when you say
"remove the listener and destroy the plugin instance afterward"

currently I have this thing only

 window.addEventListener('shake', shakeEventDidOccur, false);

```
    //shake event callback


    function shakeEventDidOccur () {

        var img = new Image();
        var div =$('.monkey');
        console.log(div);
        img.onload = function() {
            div.append(img);
            img.setAttribute('id','dance')
        };
```

what should I change in my code??

**Comment by alexgibson** [comment]
Please take some time to read the documentation: https://github.com/alexgibson/shake.js

**Comment by usama831** [comment]
O yeah I found it,

Thanks For the help :)
