### ISSUE TITLE
How we can determine that the shake is stopped now?

### ISSUE THREAD

**Issue by usama831** [alexgibson/shake.js#36]
when shake starts, we can listen it using 
window.addEventListener('shake', shakeEventDidOccur, false);

how we can determine that the shake is stopped now, and end user is not shaking the device ? Actually I have to show a different popup when device is shaking and when some one stop shaking the device, i have to show a different popup / alert. Can you guide me on it. Thanks

**Comment by alexgibson** [comment]
When someone dismisses the popup that gets triggered when they shake the device, you're pretty safe to assume they have stopped shaking?

You can't really fire an event for "not shaking" as this would be triggered continuously (unless the user was shaking)

**Comment by alexgibson** [comment]
Alternatively you could use a timeout that gets reset each time a shake occurs.
