### ISSUE TITLE
Trigger event on shake stops ? 

### ISSUE THREAD

**Issue by Tisseur2Toile** [alexgibson/shake.js#40]
Hello,
Maybe it is a stupid question, but is there a simple mean to know when shake stops ?
It would really help in my current project.

**Comment by alexgibson** [comment]
Could your project not just poll for shake events and then fire a callback when one does not occur after x seconds?

**Comment by Tisseur2Toile** [comment]
That's what I was trying to do but I'm a little puzzled to find a correct way to do it...

**Comment by Tisseur2Toile** [comment]
I found a way like this and it's working, but maybe it is not a very clean way, any thoughts ?
```
var testInt = false;
function shakeEventDidOccur () {
    if (testInt !== false)
    {
        clearInterval(testInt);
    }
    testInt = setInterval(clearMyInt, 1200);
    console.log('shaking');
}

function clearMyInt() {
    clearInterval(testInt);
    alert('done');
}
```

**Comment by alexgibson** [comment]
Something like that should work - sorry I don't have much time to offer assistance with code that's not specific to the library itself.

**Comment by Tisseur2Toile** [comment]
@alexgibson ok, I understand, thanks for your time and great library btw ! ;)

**Comment by alexgibson** [comment]
No problem, good luck - and thanks 👍
