### ISSUE TITLE
change the event from 'devicemotion' to 'deviceorientation'

### ISSUE THREAD

**Issue by givingwu** [alexgibson/shake.js#44]
1. when i ran this lib's code in Chrome, i found that : 

[Deprecation] The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See [https://goo.gl/rStTGz](https://goo.gl/rStTGz) for more details.

2. when i modified the event from 'devicemotion' to 'deviceorientation', i also got the same warning!

DeviceMotionEventAndVibrate.html:81 [Deprecation] The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See [https://goo.gl/rStTGz](https://goo.gl/rStTGz) for more details.

3. Why you choose  'devicemotion' not  'deviceorientation' to wrote this lib? 3ks in advance.

**Comment by alexgibson** [comment]
The solution here is to update your site to HTTPS.
