### ISSUE TITLE
How to use shake.js under Angular 6?

### ISSUE THREAD

**Issue by matthewgan** [alexgibson/shake.js#46]
How to use shake.js under Angular 6?

**Comment by alexgibson** [comment]
This issue lacks detail, unless you provide an adequate description, it will be closed.

**Comment by matthewgan** [comment]
Hi, I'm trying to use shake.js in Angular 6, but i may use this method in the wrong way.
after "npm install shake.js"

In one of my component:

import * as Shake from '../../../node_modules/shake.js'

export class myComponent implements OnInit {
  constructor(   
    private shake: Shake,
  ) { }  

  ngOnInit() {   
    this.shake.start();
    window.addEventListener('shake', myFunc, false);
  }

  myFunc() {
    //do something
  }

}

But myFunc is never be called in my angular app.

I have tried with ngZone and other ways but still not working, what would i miss to use shake.js in angular?

Please help, much thanks

**Comment by alexgibson** [comment]
This feels like an Angular specific question rather than an issue with shake.js itself. The library is available as UMD, but how you consume it is up to you. I don't know Angular, so sorry I can't help.

**Comment by matthewgan** [comment]
Yes, it is something about angular. Sorry about the interrupting, pls close it.
Still thanks for your quick feedback.
