### ISSUE TITLE
Not working in iOS12.2

### ISSUE THREAD

**Issue by 13880971267** [alexgibson/shake.js#49]
Can't work properly on iOS12.2 web pages。Nothing happens after shaking the iPhone

**Comment by alexgibson** [comment]
See: https://github.com/w3c/deviceorientation/issues/57#issuecomment-458464696

Until Apple offer a way to request access for the API, there’s nothing that can be done.

**Comment by 13880971267** [comment]
Thank you very much.

**Comment by xing00** [comment]
I use http, it doesn't work, when i use https , it works! I don't know why.

**Comment by yoyo837** [comment]
~~@xing00 You are right, why is it designed like this?~~

**Comment by yoyo837** [comment]
@xing00 Only Webview.

**Comment by xing00** [comment]
> @xing00 Only Webview.

Yes,I only use this code on webview.

**Comment by yoyo837** [comment]
iOS (Privacy switch turned on): 

| - | http | https |
| -------- | ----------- | ---- |
| Safari | No | Yes | 
| WebView | No | Yes | 

iOS (Privacy switch turned off): 

| - | http | https |
| -------- | ----------- | ---- |
| Safari | No | No | 
| WebView | No | Yes |

**Comment by xing00** [comment]
@yoyo837 Got it.

**Comment by githubhwen** [comment]
It is working in wechat if use https,It also works if you allow Safari browsers to move and direction access.
