### ISSUE TITLE
Safari iOS event not firing

### ISSUE THREAD

**Issue by DannyT** [alexgibson/shake.js#52]
Appreciate this is an old repo but I can't find anything newer/better or any indicator this should/shouldn't work still.

On Safari on iOS, if I `alert('ondevicemotion' in window);`` it alerts "true" indicating the feature should be supported. However, even with the threshold set as low as 1, I still get no event on safari on iOS.

Any help much appreciated 🙏

**Comment by alexgibson** [comment]
For Safari on iOS you need to request permissions to enable access to device motion. See https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes#3314664

**Comment by alexgibson** [comment]
Also https://dev.to/li/how-to-requestpermission-for-devicemotion-and-deviceorientation-events-in-ios-13-46g2

**Comment by DannyT** [comment]
@alexgibson thankyou that's exactly what I was looking for 🙏
